# This workflow will be fired everytime we push changes to any branch named: feature* or bug*
name: Feature

on:
  push:
    branches: [ 'feature*', 'bug*' ]
      # - master
      # - development
      # - release*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - name: Build with dotnet
      run: dotnet build --configuration Release
